2020-04-07 14:26:20,394 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:28:10,059 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:30:10,900 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:30:58,819 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:33:26,963 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:35:00,632 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:35:55,496 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:37:25,550 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:38:00,926 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:39:55,480 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:40:45,807 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:41:59,880 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:42:37,655 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:43:11,009 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:44:15,765 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:45:49,644 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:54:29,326 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 14:54:43,793 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 15:30:52,122 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 15:31:50,971 ERROR: Exception on /main/send_message/puppy [GET] [in /home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/centvr/Documents/pyscript/microblog/app/main/routes.py", line 149, in send_message
    if form.validate_on_sumit():
AttributeError: 'MessageForm' object has no attribute 'validate_on_sumit'
2020-04-07 15:32:39,597 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 15:35:36,320 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 16:07:22,110 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 16:16:08,132 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 16:16:37,946 ERROR: Exception on /main/notifications [GET] [in /home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/centvr/Documents/pyscript/microblog/app/main/routes.py", line 177, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2020-04-07 16:16:46,855 ERROR: Exception on /main/notifications [GET] [in /home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/centvr/Documents/pyscript/microblog/app/main/routes.py", line 177, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2020-04-07 16:16:53,653 ERROR: Exception on /main/notifications [GET] [in /home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/centvr/Documents/pyscript/microblog/app/main/routes.py", line 177, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
